server: 
  port: 9527
 
spring: 
  application:
    name: api-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.1:7002/eureka
  instance:
    instance-id: api-gateway9527
    prefer-ip-address: true


zuul:
  #ignored-services: microservicecloud-dept
  prefix: /atguigu
  ignored-services: "*"
  routes:
    mydept.serviceId: api-provider
    mydept.path: /api/**

